substitutions:
  name: "car-assistant"
  friendly_name: "Car Assistant"
  id: "car_assistant"

  ### User Config ###

  # Core:
  core_ota_password: !secret ota_password                           # OTA update password (Choose a strong password! The OTA port can be accessed on your carrier's NAT!)

  # Modem:
  modem_rx_pin: "GPIO26"                                            # Modem RX pin
  modem_tx_pin: "GPIO27"                                            # Modem TX pin
  modem_power_pin: "GPIO04"                                         # Modem Power pin
  modem_power_pin_inverted: true                                    # Modem Power pin inverted (true/false)
  modem_status_pin: "GPIO34"                                        # Modem Status pin
  modem_model: "SIM7600"                                            # Modem model (See https://deploy-preview-4056--esphome.netlify.app/components/modem.html for a list of supported modems)
  modem_apn: "carrier.apn.address"                                  # Cellular APN
  modem_pin_code: ""                                                # SIM PIN code (if applicable)
  modem_flight_mode_pin: "GPIO25"                                   # Modem Flight Mode pin
  modem_address: ${wireguard_client_address}                        # IP to use for OTA updates & logs

  # Battery:
  battery_pin: "GPIO35"                                             # Battery voltage ADC pin
  battery_solar_indicator_pin: "GPIO36"                             # Solar charging indicator ADC pin

  # WiFi:
  wifi_hotspot_ssid: "${friendly_name}"                             # WiFi Hotspot SSID
  wifi_hotspot_password: !secret wifi_password                      # WiFi Hotspot password
  
  # Web Server:
  webserver_username: "root"                                        # Web Server username
  webserver_password: !secret webserver_password                    # Web Server password (Choose a strong password! The webserver can be accessed on your carrier's NAT!)

  # WireGuard:
  wireguard_timezone: "Etc/UTC"                                     # Timezone (e.g., Etc/UTC, Europe/Berlin, etc.)
  wireguard_peer_address: !secret wireguard_address                 # WireGuard server address
  wireguard_peer_port: 51820                                        # WireGuard server port
  wireguard_client_address: 172.16.0.4                              # WireGuard client address
  wireguard_private_key: !secret wireguard_private_key              # WireGuard private key
  wireguard_public_key: !secret wireguard_public_key                # WireGuard peer public key
  wireguard_netmask: 0.0.0.0                                        # WireGuard netmask
  wireguard_peer_persistent_keepalive: 25s                          # WireGuard persistent keepalive interval

  # Home Assistant API:
  home_assistant_api_encryption_key: !secret api_encryption_key     # Home Assistant API encryption key

  # MQTT:
  # mqtt_broker: !secret mqtt_address                               # MQTT broker address
  # mqtt_port: 1883                                                 # MQTT broker port
  # mqtt_username: !secret mqtt_username                            # MQTT username
  # mqtt_password: !secret mqtt_password                            # MQTT password

  # Sensors:
  sensors_bme280_address: "0x76"                                    # BME280 I2C address (0x76 or 0x77)
  sensors_tsl2561_address: "0x39"                                   # TSL2561 I2C address (0x29, 0x39, or 0x49)
  sensors_pir_pin: "GPIO19"                                         # PIR motion sensor pin
  sensors_radar_tx_pin: "GPIO19"                                    # Radar UART TX pin
  sensors_radar_rx_pin: "GPIO23"                                    # Radar UART RX pin

  # BLE:
  ble_ibeacon_uuid: "12345678-1234-1234-1234-1234567890ab"          # iBeacon UUID

  # SDCard:
  sdcard_clk_pin: "GPIO14"                                          # SDCard CLK pin
  sdcard_cmd_pin: "GPIO15"                                          # SDCard CMD pin
  sdcard_data0_pin: "GPIO2"                                         # SDCard DATA0 pin
  sdcard_data3_pin: "GPIO13"                                        # SDCard DATA3 pin

  # Debug:
  debug_status_led_pin: "GPIO12"                                    # Status LED pin
  debug_status_led_inverted: false                                  # Status LED pin inverted (true/false)

  ### End of User Config ###

packages:
  remote_package:
    url: https://github.com/ShonP40/Car-Assistant
    ref: master
    refresh: 10min
    files:
      - ESPHome/Core.yaml            # Core ESPHome config
      - ESPHome/Debug.yaml           # Debug sensors
      - ESPHome/WiFi.yaml            # WiFi hotspot
      # - ESPHome/Internet.yaml      # WiFi hotspot internet access (Incompatible with WireGuard!)
      - ESPHome/WebServer.yaml       # Web Server
      - ESPHome/Modem.yaml           # Modem config
      - ESPHome/Battery.yaml         # Battery monitoring
      # - ESPHome/SDCard.yaml        # SDCard & web file server
      - ESPHome/WireGuard.yaml       # WireGuard
      - ESPHome/BLE.yaml             # BLE Proxy
      - ESPHome/iBeacon.yaml         # BLE iBeacon
      - ESPHome/BME280.yaml          # BME280 config
      - ESPHome/TSL2561.yaml         # TSL2561 config

      # Use either PIR or Radar, not both as they share the same connector
      # - ESPHome/PIR.yaml           # PIR motion sensor config
      - ESPHome/Radar.yaml           # mmWave Radar config

      # Use either API (Native Home Assistant API) or MQTT, not both
      - ESPHome/API.yaml             # Native API (requires WireGuard.yaml)
      # - ESPHome/MQTT.yaml          # MQTT config