################################################################################# Example Home Assistant config
mqtt:
  sensor:
    - name: "Car Temperture"
      state_topic: "car-assistant/temperature"
      unit_of_measurement: "°C"
      icon: mdi:thermometer
    - name: "Car Humidity"
      state_topic: "car-assistant/humidity"
      unit_of_measurement: "%"
      icon: mdi:water-percent
    - name: "Car Pressure"
      state_topic: "car-assistant/pressure"
      unit_of_measurement: "hPa"
      icon: mdi:gauge
    - name: "Car Light Level"
      state_topic: "car-assistant/lux"
      unit_of_measurement: "lux"
      icon: mdi:weather-sunny
    - name: "Car ESP CPU Temperature"
      state_topic: "car-assistant/cpu-temperature"
      unit_of_measurement: "°C"
      icon: mdi:thermometer
    - name: "Car ESP CPU Frequency"
      state_topic: "car-assistant/cpu-frequency"
      unit_of_measurement: "MHz"
      icon: mdi:chip
    - name: "Car ESP Free RAM"
      state_topic: "car-assistant/free-ram"
      unit_of_measurement: "B"
      icon: mdi:memory
    - name: "Car Hall Sensor"
      state_topic: "car-assistant/hall"
      icon: mdi:magnet
    - name: "Car Modem Info"
      state_topic: "car-assistant/modem-info"
      icon: mdi:cellphone
    - name: "Car Modem CCID"
      state_topic: "car-assistant/ccid"
      icon: mdi:cellphone
    - name: "Car Modem IMSI"
      state_topic: "car-assistant/imsi"
      icon: mdi:cellphone
    - name: "Car Modem Operator"
      state_topic: "car-assistant/operator"
      icon: mdi:cellphone
    - name: "Car Signal Quality"
      state_topic: "car-assistant/signal-quality"
      icon: mdi:cellphone
    - name: "Car Public IP"
      state_topic: "car-assistant/public-ip"
      icon: mdi:cellphone
    - name: "Car Battery Percentage"
      state_topic: "car-assistant/battery-percentage"
      unit_of_measurement: "%"
      icon: mdi:battery
    - name: "Car Battery Voltage"
      state_topic: "car-assistant/battery-voltage"
      unit_of_measurement: "V"
      icon: mdi:battery
    - name: "Car Battery Status"
      state_topic: "car-assistant/battery-status"
      icon: mdi:battery
    - name: "Car Location Type"
      state_topic: "car-assistant/location-type"
      icon: mdi:map-marker
    - name: "Car Latitude"
      state_topic: "car-assistant/latitude"
      icon: mdi:map-marker
    - name: "Car Longitude"
      state_topic: "car-assistant/longitude"
      icon: mdi:map-marker
    - name: "Car Speed"
      state_topic: "car-assistant/speed"
      unit_of_measurement: "km/h"
      icon: mdi:speedometer
    - name: "Car Altitude"
      state_topic: "car-assistant/altitude"
      unit_of_measurement: "m"
      icon: mdi:map-marker
    - name: "Car Location Accuracy"
      state_topic: "car-assistant/location-accuracy"
      unit_of_measurement: "m"
      icon: mdi:map-marker
    - name: "Car OBD Payload"
      state_topic: "car-assistant/obd-payload"
      icon: mdi:car-brake-alert
    - name: "Car OBD Debug"
      state_topic: "car-assistant/obd-debug"
      icon: mdi:car-tire-alert
    - name: "Car OBD Engine Load"
      state_topic: "car-assistant/obd-engine-load"
      unit_of_measurement: "%"
      icon: mdi:engine
    - name: "Car OBD Coolant Temperature"
      state_topic: "car-assistant/obd-engine-coolant-temp"
      unit_of_measurement: "°C"
      icon: mdi:coolant-temperature
    - name: "Car OBD Short Term Fuel Trim Bank 1"
      state_topic: "car-assistant/obd-short-term-fuel-trim-bank-1"
      unit_of_measurement: "%"
      icon: mdi:fuel
    - name: "Car OBD Long Term Fuel Trim Bank 1"
      state_topic: "car-assistant/obd-long-term-fuel-trim-bank-1"
      unit_of_measurement: "%"
      icon: mdi:fuel
    - name: "Car OBD Short Term Fuel Trim Bank 2"
      state_topic: "car-assistant/obd-short-term-fuel-trim-bank-2"
      unit_of_measurement: "%"
      icon: mdi:fuel
    - name: "Car OBD Long Term Fuel Trim Bank 2"
      state_topic: "car-assistant/obd-long-term-fuel-trim-bank-2"
      unit_of_measurement: "%"
      icon: mdi:fuel
    - name: "Car OBD Fuel Pressure"
      state_topic: "car-assistant/obd-fuel-pressure"
      unit_of_measurement: "kPa"
      icon: mdi:car-brake-low-pressure
    - name: "Car OBD Manifold Pressure"
      state_topic: "car-assistant/obd-manifold-pressure"
      unit_of_measurement: "kPa"
      icon: mdi:car-brake-low-pressure
    - name: "Car OBD RPM"
      state_topic: "car-assistant/obd-rpm"
      unit_of_measurement: "rpm"
      icon: mdi:turbine
    - name: "Car OBD Speed (km/h)"
      state_topic: "car-assistant/obd-kph"
      unit_of_measurement: "km/h"
      icon: mdi:speedometer
    - name: "Car OBD Speed (mph)"
      state_topic: "car-assistant/obd-mph"
      unit_of_measurement: "mph"
      icon: mdi:speedometer
    - name: "Car OBD Timing Advance"
      state_topic: "car-assistant/obd-timing-advance"
      unit_of_measurement: "°"
      icon: mdi:shimmer
    - name: "Car OBD Intake Air Temperature"
      state_topic: "car-assistant/obd-intake-air-temp"
      unit_of_measurement: "°C"
      icon: mdi:thermometer
    - name: "Car OBD MAF Rate"
      state_topic: "car-assistant/obd-maf-rate"
      unit_of_measurement: "g/s"
      icon: mdi:weather-windy
    - name: "Car OBD Throttle"
      state_topic: "car-assistant/obd-throttle"
      unit_of_measurement: "%"
      icon: mdi:bike-pedal
    - name: "Car OBD AUX Input Status"
      state_topic: "car-assistant/obd-aux-input-status"
      icon: mdi:import
    - name: "Car OBD Run Time"
      state_topic: "car-assistant/obd-run-time"
      unit_of_measurement: "s"
      icon: mdi:timer
    - name: "Car OBD Distance Traveled With MIL"
      state_topic: "car-assistant/obd-dist-travel-with-mil"
      unit_of_measurement: "km"
      icon: mdi:counter
    - name: "Car OBD Fuel Rail Pressure"
      state_topic: "car-assistant/obd-fuel-rail-pressure"
      unit_of_measurement: "kPa"
      icon: mdi:car-brake-low-pressure
    - name: "Car OBD Fuel Rail Gauge Pressure"
      state_topic: "car-assistant/obd-fuel-rail-guage-pressure"
      unit_of_measurement: "kPa"
      icon: mdi:car-brake-low-pressure
    - name: "Car OBD Commanded EGR"
      state_topic: "car-assistant/obd-commanded-egr"
      unit_of_measurement: "%"
      icon: mdi:apple-keyboard-command
    - name: "Car OBD EGR Error"
      state_topic: "car-assistant/obd-egr-error"
      unit_of_measurement: "%"
      icon: mdi:alert-circle
    - name: "Car OBD Commanded Evaporative Purge"
      state_topic: "car-assistant/obd-commanded-evap-purge"
      unit_of_measurement: "%"
      icon: mdi:apple-keyboard-command
    - name: "Car OBD Fuel Level"
      state_topic: "car-assistant/obd-fuel-level"
      unit_of_measurement: "%"
      icon: mdi:fuel
    - name: "Car OBD Number of Warm-ups Since Codes Cleared"
      state_topic: "car-assistant/obd-warm-ups-since-codes-cleared"
      icon: mdi:code-braces
    - name: "Car OBD Distance Since Codes Cleared"
      state_topic: "car-assistant/obd-dist-since-codes-cleared"
      unit_of_measurement: "km"
      icon: mdi:code-json
    - name: "Car OBD Evap System Vapor Pressure"
      state_topic: "car-assistant/obd-evap-sys-vap-pressure"
      unit_of_measurement: "Pa"
      icon: mdi:car-brake-low-pressure
    - name: "Car OBD ABS Barometric Pressure"
      state_topic: "car-assistant/obd-abs-baro-pressure"
      unit_of_measurement: "kPa"
      icon: mdi:gauge
    - name: "Car OBD Catalytic Temperature B1 S1"
      state_topic: "car-assistant/obd-cat-temp-b1-s1"
      unit_of_measurement: "°C"
      icon: mdi:thermometer-high
    - name: "Car OBD Catalytic Temperature B2 S1"
      state_topic: "car-assistant/obd-cat-temp-b2-s1"
      unit_of_measurement: "°C"
      icon: mdi:thermometer-high
    - name: "Car OBD Catalytic Temperature B1 S2"
      state_topic: "car-assistant/obd-cat-temp-b1-s2"
      unit_of_measurement: "°C"
      icon: mdi:thermometer-high
    - name: "Car OBD Catalytic Temperature B2 S2"
      state_topic: "car-assistant/obd-cat-temp-b2-s2"
      unit_of_measurement: "°C"
      icon: mdi:thermometer-high
    - name: "Car OBD Ctrl Mod Voltage"
      state_topic: "car-assistant/obd-ctrl-mod-voltage"
      unit_of_measurement: "V"
      icon: mdi:flash-triangle-outline
    - name: "Car OBD ABS Load"
      state_topic: "car-assistant/obd-abs-load"
      unit_of_measurement: "%"
      icon: mdi:car-brake-abs
    - name: "Car OBD Commanded Air Fuel Ratio"
      state_topic: "car-assistant/obd-commanded-air-fuel-ratio"
      unit_of_measurement: "ratio"
      icon: mdi:apple-keyboard-command
    - name: "Car OBD Relative Throttle"
      state_topic: "car-assistant/obd-relative-throttle"
      unit_of_measurement: "%"
      icon: mdi:relative-scale
    - name: "Car OBD Ambient Air Temperature"
      state_topic: "car-assistant/obd-ambient-air-temp"
      unit_of_measurement: "°C"
      icon: mdi:thermometer
    - name: "Car OBD ABS Throttle Position B"
      state_topic: "car-assistant/obd-abs-throttle-pos-b"
      unit_of_measurement: "%"
      icon: mdi:car-brake-abs
    - name: "Car OBD ABS Throttle Position C"
      state_topic: "car-assistant/obd-abs-throttle-pos-c"
      unit_of_measurement: "%"
      icon: mdi:car-brake-abs
    - name: "Car OBD Accelerator Pedal Position D"
      state_topic: "car-assistant/obd-accel-pedal-pos-d"
      unit_of_measurement: "%"
      icon: mdi:car-brake-abs
    - name: "Car OBD Accelerator Pedal Position E"
      state_topic: "car-assistant/obd-accel-pedal-pos-e"
      unit_of_measurement: "%"
      icon: mdi:car-brake-abs
    - name: "Car OBD Accelerator Pedal Position F"
      state_topic: "car-assistant/obd-accel-pedal-pos-f"
      unit_of_measurement: "%"
      icon: mdi:car-brake-abs
    - name: "Car OBD Commanded Throttle Actuator"
      state_topic: "car-assistant/obd-commanded-throttle-actuator"
      unit_of_measurement: "%"
      icon: mdi:car-brake-abs
    - name: "Car OBD Time Run with MIL"
      state_topic: "car-assistant/obd-time-run-with-mil"
      unit_of_measurement: "s"
      icon: mdi:timer-alert
    - name: "Car OBD Time Since Codes Cleared"
      state_topic: "car-assistant/obd-time-since-codes-cleared"
      unit_of_measurement: "s"
      icon: mdi:timer-check
    - name: "Car OBD Max MAF Rate"
      state_topic: "car-assistant/obd-max-maf-rate"
      unit_of_measurement: "g/s"
      icon: mdi:weather-windy
    - name: "Car OBD Ethonol Percent"
      state_topic: "car-assistant/obd-ethonol-percent"
      unit_of_measurement: "%"
      icon: mdi:percent-circle-outline
    - name: "Car OBD ABS Evap System Vapor Pressure"
      state_topic: "car-assistant/obd-abs-evap-sys-vap-pressure"
      unit_of_measurement: "Pa"
      icon: mdi:car-brake-abs
    - name: "Car OBD ABS Evap System Vapor Pressure 2"
      state_topic: "car-assistant/obd-abs-evap-sys-vap-pressure-2"
      unit_of_measurement: "Pa"
      icon: mdi:car-brake-abs
    - name: "Car OBD ABS Fuel Rail Pressure"
      state_topic: "car-assistant/obd-abs-fuel-rail-pressure"
      unit_of_measurement: "kPa"
      icon: mdi:car-brake-abs
    - name: "Car OBD Relative Pedal Position"
      state_topic: "car-assistant/obd-relative-pedal-pos"
      unit_of_measurement: "%"
      icon: mdi:bike-pedal
    - name: "Car OBD Hybrid Battery Life"
      state_topic: "car-assistant/obd-hybrid-bat-life"
      unit_of_measurement: "%"
      icon: mdi:battery
    - name: "Car OBD Oil Temperature"
      state_topic: "car-assistant/obd-oil-temp"
      unit_of_measurement: "°C"
      icon: mdi:oil-temperature
    - name: "Car OBD Fuel Inject Timing"
      state_topic: "car-assistant/obd-fuel-inject-timing"
      unit_of_measurement: "°"
      icon: mdi:gas-station
    - name: "Car OBD Fuel Rate"
      state_topic: "car-assistant/obd-fuel-rate"
      unit_of_measurement: "L/h"
      icon: mdi:fuel
    - name: "Car OBD Demanded Torque"
      state_topic: "car-assistant/obd-demanded-torque"
      unit_of_measurement: "%"
      icon: mdi:engine-outline
    - name: "Car OBD Torque"
      state_topic: "car-assistant/obd-torque"
      unit_of_measurement: "%"
      icon: mdi:engine-outline
    - name: "Car OBD Reference Torque"
      state_topic: "car-assistant/obd-reference-torque"
      unit_of_measurement: "%"
      icon: mdi:engine-outline
    - name: "Car OBD Battery Voltage"
      state_topic: "car-assistant/obd-battery-voltage"
      unit_of_measurement: "V"
      icon: mdi:car-battery
    - name: "Car OBD VIN"
      state_topic: "car-assistant/obd-vin"
      icon: mdi:serial-port
    - name: "Car ESP Uptime"
      state_topic: "car-assistant/uptime"
      unit_of_measurement: "s"
      icon: mdi:timer-refresh
    - name: "Car Assistant Version"
      state_topic: "car-assistant/version"
      icon: mdi:list-status
  binary_sensor:
    - name: "Car Motion Sensor"
      state_topic: "car-assistant/pir"
      icon: mdi:run
      payload_on: "1"
      payload_off: "0"
      device_class: motion
  device_tracker:
    - name: "Car"
      icon: mdi:car
      state_topic: "car-assistant/location"
      json_attributes_topic: "car-assistant/json-location"
      json_attributes_template: "{{ value_json | tojson }}"
################################################################################# Example Home Assistant automation for updating the device tracker
id: "car_assistant_update_location"
alias: "Car Assistant: Update location"
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.car_latitude
  - platform: state
    entity_id:
      - sensor.car_longitude
  - platform: state
    entity_id:
      - sensor.car_location_accuracy
  - platform: state
    entity_id:
      - sensor.car_battery_percentage
  - platform: state
    entity_id:
      - sensor.car_speed
condition: []
action:
  - service: mqtt.publish
    data:
      retain: true
      topic: car-assistant/json-location
      payload_template: >-
        {"longitude": "{{ states('sensor.car_longitude') | float }}", "latitude": "{{ states('sensor.car_latitude') | float }}", "gps_accuracy": "{{states('sensor.car_location_accuracy') | int }}", "altitude": "{{states('sensor.car_altitude') | int }}", "battery_level": "{{states('sensor.car_battery_percentage') | int }}", "speed": "{{states('sensor.car_speed') | int }}"}

  - service: mqtt.publish
    data:
      retain: true
      topic: car-assistant/location
      payload: >
        {% set device_longitude = states('sensor.car_longitude') | float %}
        {% set device_latitude = states('sensor.car_latitude') | float %}
        {% set locations = states.zone | selectattr('attributes.radius', 'defined') | map(attribute='entity_id') | list %}
        {% set regex = '^.+\\.(.+)$' %} {# regular expression to match the second part of the entity_id #}
        {% set result = namespace(results = none) %}
        {% for location in locations %}
          {% set zone_entity_id = location.lower().replace(' ', '_') %}
          {% set zone_latitude = state_attr(zone_entity_id, 'latitude') %}
          {% set zone_longitude = state_attr(zone_entity_id, 'longitude') %}
          {% set zone_radius = state_attr(zone_entity_id, 'radius') %}
          {% set lat_diff = device_latitude - zone_latitude %}
          {% set lon_diff = device_longitude - zone_longitude %}
          {% set distance = ((lat_diff**2 + lon_diff**2)**0.5) * 111139 %} {# distance in meters #}
          {% set match = location | regex_findall_index(regex) %} {# find the match with the regular expression #}
          {% if distance <= zone_radius %}
            {% set zone_friendly_name = state_attr(zone_entity_id, 'friendly_name') %}
            {% set result.results = zone_friendly_name %}
            {% if result.results == 'House' %}
              {{ 'Home' }}
            {% else %}
              {{ result.results }}
            {% endif %}
          {% endif %}
        {% endfor %}
        {% if result.results is none %}
          {{ 'not_home' }}
        {% endif %}

mode: single
