####################################################################################################
#####                                    Car Assistant                                         #####
#####                  Repository: https://github.com/ShonP40/Car-Assistant                    #####
####################################################################################################
##### Purpose: Debug sensors config                                                            #####
####################################################################################################
##### NOTE:                                                                                    #####
##### - Make changes ONLY if absolutely necessary and you have the required knowledge.         #####
##### - For normal system use, modifications to this file are NOT required.                    #####
####################################################################################################

debug:

text_sensor:
  - platform: debug
    device:
      name: "${friendly_name} Device Info"
    reset_reason:
      name: "${friendly_name} Reset Reason"

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime Sensor"
  - platform: internal_temperature
    name: "Internal Temperature"
  - platform: debug
    free:
      name: "${friendly_name} Heap Free"
    block:
      name: "${friendly_name} Heap Max Block"
    loop_time:
      name: "${friendly_name} Loop Time"
    psram:
      name: "${friendly_name} Free PSRAM"
    cpu_frequency:
      name: "${friendly_name} CPU Frequency"

button:
  - platform: restart
    id: restart_button
    name: "${friendly_name} Restart"

inary_sensor:
  - platform: status
    name: "${friendly_name} Status"

status_led:
  pin:
    number: GPIO12
    inverted: true