####################################################################################################
#####                                    Car Assistant                                         #####
#####                  Repository: https://github.com/ShonP40/Car-Assistant                    #####
####################################################################################################
##### Purpose: WiFi hotspot internet access config                                             #####
####################################################################################################
##### NOTE:                                                                                    #####
##### - Make changes ONLY if absolutely necessary and you have the required knowledge.         #####
##### - For normal system use, modifications to this file are NOT required.                    #####
####################################################################################################

external_components:
  - source:
      type: git
      url: https://github.com/oarcher/esphome.git
      ref: 8ad1bd4a4bb6f96629f2141eafb7360cf4850b70
    components: [ wifi ]
    refresh: 10min

modem:
  on_connect:
    - logger.log: "Restarting WiFi DHCP server to use modem interface"
    - lambda: |-
        esphome::wifi::global_wifi_component->wifi_ap_nat(id(atmodem)->modem_handler->ppp_netif);