####################################################################################################
#####                                    Car Assistant                                         #####
#####                  Repository: https://github.com/ShonP40/Car-Assistant                    #####
####################################################################################################
##### Purpose: Modem and GPS config & sensors                                                  #####
####################################################################################################
##### NOTE:                                                                                    #####
##### - Make changes ONLY if absolutely necessary and you have the required knowledge.         #####
##### - For normal system use, modifications to this file are NOT required.                    #####
####################################################################################################

external_components:
  # Docs: https://deploy-preview-4056--esphome.netlify.app/components/modem.html
  - source:
      type: git
      url: https://github.com/oarcher/esphome.git
      ref: b19b09378b5162bdfdc5eb046ef92c269d09f104
    components: [ modem ]
    refresh: 10min
  
  - source:
      type: git
      url: https://github.com/oarcher/esphome.git
      ref: 5e11d8b4db4963519867a544abb7898bdc113598
    components: [ modem_info ]
    refresh: 10min

  - source:
      type: git
      url: https://github.com/oarcher/piotech.git
      ref: 06f042f36099ad98e1ec9c054902b9a5f77fcb21
    components: [ nulluart ]
    refresh: 10min

http_request:

modem:
  id: atmodem
  rx_pin: ${modem_rx_pin}
  tx_pin: ${modem_tx_pin}
  baud_rate: 115200
  model: ${modem_model}
  apn: ${modem_apn}
  pin_code: ${modem_pin_code}
  enable_on_boot: true
  reboot_timeout: 5min
  on_connect:
    - logger.log: "Modem connected"
    - http_request.send:
        method: get
        url: "http://api.ipify.org"
        capture_response: true
        on_response:
          then:
            - lambda: id(${id}_public_ip).publish_state(body);
    - lambda: |-
        auto res = id(atmodem).send_at("AT+CSPN?");
        std::string output = res.output;

        auto first_quote = output.find('"');
        auto second_quote = output.find('"', first_quote + 1);

        std::string carrier = "";
        if (first_quote != std::string::npos && second_quote != std::string::npos) {
            carrier = output.substr(first_quote + 1, second_quote - first_quote - 1);
        }

        id(${id}_network_operator).publish_state(carrier);
    - lambda: |-
        auto addrs = id(atmodem).get_ip_addresses();
        std::string ip_str = "N/A";
        if (!addrs.empty()) {
          ip_str = addrs[0].str();
        }
        id(${id}_cellular_ip).publish_state(ip_str);
  on_disconnect:
    - logger.log: "Modem disconnected"
  use_address: ${modem_address}
  urc:
    name: "Modem URCs"
    filters:
      # forward NMEA sentences to virtual uart, so GPS can read them
      - lambda: |-
          if (x.find("$GPGGA") != std::string::npos || x.find("$GPRMC") != std::string::npos) {
            ESP_LOGI("NMEA", "got NMEA sentence: %s", x.c_str());
            id(nulluart_id)->write_array((const uint8_t*)x.c_str(), x.length());
            id(gps_id)->update();
            return {};
          }
          return x;
  on_sync:
    - modem.send_at: AT+CGPS=1 # poweron GPS
    - modem.send_at: AT+CGPSINFOCFG=10,3 # nmea sentence every 10s GPGGA and GPRMC

# Turn on/off value from https://simcom.ee/documents/SIM7600E/SIM7600%20Series%20Hardware%20Design_V1.03.pdf
# p 24-25
script:
  - id: modem_on
    mode: single
    then:
      - logger.log: modem POWERON begin...
      - switch.turn_on: modem_power
      - delay: 500ms
      - switch.turn_off: modem_power
      - delay: 12s
      - logger.log: modem POWERON done

  - id: modem_off
    mode: single
    then:
      - logger.log: modem POWEROFF begin...
      - switch.turn_on: modem_power
      - delay: 2700ms
      - switch.turn_off: modem_power
      - delay: 15s
      - logger.log: modem POWEROFF done

nulluart:
 id: nulluart_id
 on_update: 
  - component.update: gps_id

gps:
  uart_id: nulluart_id
  id: gps_id
  latitude:
    name: "${friendly_name} Latitude"
  longitude:
    name: "${friendly_name} Longitude"
  altitude:
    name: "${friendly_name} Altitude"
  speed:
    name: "${friendly_name} Speed"
  course:
    name: "${friendly_name} Course"
  satellites:
    name: "${friendly_name} Satellites"
  hdop:
    name: "${friendly_name} Horizontal Dilution Of Precision"
    id: ${id}_hdop
    icon: mdi:map-marker-distance

text_sensor:
  - platform: modem_info
    network_type:
      name: "${friendly_name} Network Type"
      entity_category: "diagnostic"
      icon: mdi:signal
    signal_strength:
      name: "${friendly_name} Signal Strength"
      entity_category: "diagnostic"
  - platform: template
    name: "${friendly_name} Public IP"
    id: ${id}_public_ip
    entity_category: "diagnostic"
    icon: mdi:earth
  - platform: template
    name: "${friendly_name} Network Operator"
    id: ${id}_network_operator
    entity_category: "diagnostic"
    icon: mdi:sim
  - platform: template
    name: "${friendly_name} Cellular IP"
    id: ${id}_cellular_ip
    entity_category: "diagnostic"
    icon: mdi:wan

sensor:
  - platform: modem_info
    rssi:
      name: "${friendly_name} RSSI"
      entity_category: "diagnostic"
    ber:
      name: "${friendly_name} Bit Error Rate"
      entity_category: "diagnostic"
  - platform: template
    name: "${friendly_name} GPS Accuracy"
    unit_of_measurement: "m"
    accuracy_decimals: 1
    icon: mdi:crosshairs-gps
    lambda: return id(${id}_hdop).state * 5.0;

switch:
  - platform: gpio
    id: flight_mode
    name: "${friendly_name} Flight Mode"
    restore_mode: ALWAYS_ON
    pin:
      number: ${modem_flight_mode_pin}
    internal: true
    entity_category: "diagnostic"
  - platform: gpio
    id: modem_power
    name: "${friendly_name} Modem Power"
    restore_mode: ALWAYS_OFF
    pin:
      number: ${modem_power_pin}
      inverted: ${modem_power_pin_inverted}
    internal: true

button:
  - platform: template
    name: "${friendly_name} Restart Modem"
    entity_category: "config"
    icon: mdi:restart-alert
    on_press:
      - modem.disable:
      - delay: 15s
      - modem.enable:

binary_sensor:
  - platform: gpio
    name: "${friendly_name} Modem Status"
    id: modem_status
    pin: ${modem_status_pin}
    internal: true