####################################################################################################
#####                                    Car Assistant                                         #####
#####                  Repository: https://github.com/ShonP40/Car-Assistant                    #####
####################################################################################################
##### Purpose: WireGuard config                                                                #####
####################################################################################################
##### NOTE:                                                                                    #####
##### - Make changes ONLY if absolutely necessary and you have the required knowledge.         #####
##### - For normal system use, modifications to this file are NOT required.                    #####
####################################################################################################

time:
  - platform: sntp
    id: ${id}_sntp_time
    timezone: ${wireguard_timezone}
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org
  - platform: gps
    id: ${id}_gps_time
    timezone: ${wireguard_timezone}

wireguard:
  address: ${wireguard_client_address}
  private_key: ${wireguard_private_key}
  peer_endpoint: ${wireguard_peer_address}
  peer_public_key: ${wireguard_public_key}
  netmask: ${wireguard_netmask}
  peer_port: ${wireguard_peer_port}
  peer_allowed_ips:
    - 0.0.0.0/0
  peer_persistent_keepalive: ${wireguard_peer_persistent_keepalive}

text_sensor:
  - platform: wireguard
    address:
      name: "${friendly_name} WireGuard Address"
      entity_category: "diagnostic"
      icon: mdi:vpn

sensor:
  - platform: wireguard
    latest_handshake:
      name: "${friendly_name} WireGuard Latest Handshake"
      entity_category: "diagnostic"
      icon: mdi:handshake